source 'https://github.com/cosmos33/MMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'FaceCertificationDemo' do
  pod 'MMFaceCertification' , :path => '../'
  pod 'MMCV', '1.0.12'
end
